//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSOAuthenticator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSOAppsToken
    {
        public System.Guid TokenId { get; set; }
        public System.Guid APPId { get; set; }
        public System.Guid Token { get; set; }
        public string LoginId { get; set; }
        public bool Valid { get; set; }
    
        public virtual SSOEnabledApp SSOEnabledApp { get; set; }
    }
}
