//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSOAuthenticator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSOEnabledApp
    {
        public SSOEnabledApp()
        {
            this.SSOAppsTokens = new HashSet<SSOAppsToken>();
        }
    
        public System.Guid APPId { get; set; }
        public string APPName { get; set; }
        public string APPUrl { get; set; }
        public string CreatedDate { get; set; }
    
        public virtual ICollection<SSOAppsToken> SSOAppsTokens { get; set; }
    }
}
